crm_main/client/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.client_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('add/', views.client_add, name='add'),
]

crm_main/crm_main/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from core.views import index
from userprofile.views import signup
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/products/', include('product.urls')),
    path('dashboard/orders/', include('order.urls')),
    path('dashboard/ordersnew/', include('ordernew.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/users/', include('userprofile.urls')),
    # path('sign-up/', signup, name='signup'),
    path('log-in/',views.LoginView.as_view(template_name='userprofile/login.html') ,name='login'),
    path('log-out/',views.LogoutView.as_view() ,name='logout'),
    # path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    # path('log-out/', views.LogoutView.as_view(), name='logout'),
    # path('tickets/', include('tickets.urls')),
    path('tickets/', include('ticket.urls')),
    path('properties/', include('property.urls')),
    path('tenants/', include('tenant.urls')),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
URL configuration for crm_main project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

crm_main/lead/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add_lead'),
]

crm_main/order/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='list'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'), #optimize the name here.
    path('add-order/', views.OrderCreateView.as_view(), name='add_order'), # changed orders_add to order_add
    path('<int:pk>/delete/', views.OrderDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.OrderUpdateView.as_view(), name='edit'),
    path('<int:pk>/add-product/', views.AddProductView.as_view(), name='add_product'),
]

crm_main/tenant/urls.py
from django.urls import path
from . import views

app_name = 'tenant'

urlpatterns = [
    path('', views.TenantListView.as_view(), name='list'),
    path('<int:pk>/', views.TenantDetailView.as_view(), name='detail'),
    path('create/', views.TenantCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TenantUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TenantDeleteView.as_view(), name='delete'),
]

crm_main/ticket/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'tickets'

urlpatterns = [
    path('', views.TicketListView.as_view(), name='list'),
    path('<int:pk>/', views.TicketDetailView.as_view(), name='detail'),
    path('create/', views.TicketCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TicketUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TicketDeleteView.as_view(), name='delete'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('add-ticket/', views.TicketCreateView.as_view(), name='add_ticket'),
]

crm_main/core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'core/index.html')
    # return render(request, 'dashboard/index.html')

crm_main/core/templates/core/partials/footer.html
 {% comment %} footer {% endcomment %}
 <footer class="app-footer"> <!--begin::To the end-->
    <div class="float-end d-none d-sm-inline">Anything you want</div> <!--end::To the end--> <!--begin::Copyright--> <strong>
        Copyright &copy; 2014-2024&nbsp;
        <a href="https://adminlte.io" class="text-decoration-none">Ateam</a>.
    </strong>
    All rights reserved.
    <!--end::Copyright-->
</footer> <!--end::Footer-->

crm_main/core/templates/core/partials/nav-left.html
{% load static %}
   {% comment %} left memu {% endcomment %}
   <aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark"> <!--begin::Sidebar Brand-->
    <div class="sidebar-brand"> <!--begin::Brand Link--> <a href="./index.html" class="brand-link"> <!--begin::Brand Image--> <img src="{% static 'assets/img/AdminLTELogo.png' %}" alt="Ateam Logo" class="brand-image opacity-75 shadow"> <!--end::Brand Image--> <!--begin::Brand Text--> <span class="brand-text fw-light">Biueco Management</span> <!--end::Brand Text--> </a> <!--end::Brand Link--> </div> <!--end::Sidebar Brand--> <!--begin::Sidebar Wrapper-->
    <div class="sidebar-wrapper">
        <nav class="mt-2"> <!--begin::Sidebar Menu-->
            <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
                {% comment %} <li class="nav-item menu-open"> <a href="#" class="nav-link active"> <i class="nav-icon bi bi-speedometer"></i>
                        <p>
                            Dashboard
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item"> <a href="{% url 'dashboard:index' %}" class="nav-link active"> <i class="nav-icon bi bi-circle"></i>
                                <p>Dashboard</p>
                            </a> </li>
                        <li class="nav-item"> <a href="./index.html" class="nav-link active"> <i class="nav-icon bi bi-circle"></i>
                                <p>Dashboard Tenants</p>
                            </a> </li>
                        <li class="nav-item"> <a href="./index2.html" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                <p>Dashboard Rent</p>
                            </a> </li>
                        <li class="nav-item"> <a href="./index3.html" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                <p>Dashboard Housing property</p>
                            </a> </li>
                    </ul>
                </li> {% endcomment %}

                <li class="nav-item"> <a href="{% url 'dashboard:index' %}" class="nav-link active"> <i class="nav-icon bi bi-speedometer"></i>
                    <p>Dashboard</p>
                </a> </li>


            

                 <li class="nav-item"> <a href="{% url 'tickets:list' %}" class="nav-link"> <i class="bi bi-calendar2-plus" style="color: red;"></i>
                </i>
                        <p>Ticket</p>
                    </a> </li> 


                 <li class="nav-item"> <a href="{% url 'properties:list' %}" class="nav-link"> <i class="bi bi-tree-fill" style="color: green;"></i>
                </i>
                        <p>Property</p>
                    </a> </li> 

                    


                <li class="nav-item"> <a href="{% url 'tenant:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill" style="color: blue;"></i>
                    <p>Tenants</p>
                </a> </li>

                <li class="nav-item"> <a href="{% url 'leads:list' %}" class="nav-link"> <i class="nav-icon bi bi-palette"></i>
                        <p>Leads</p>
                    </a> </li>

            

                <li class="nav-item"> <a href="{% url 'clients:list' %}" class="nav-link"> <i class="nav-icon bi bi-palette"></i>
                        <p>Clients</p>
                    </a> </li>
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-palette"></i>
                        <p>Orders</p>
                    </a> </li>
                    
                    <li class="nav-item"> <a href="{% url 'products:list' %}" class="nav-link"> <i class="nav-icon bi bi-palette"></i>
                        <p>Products</p>
                    </a> </li>
            

                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-palette"></i>
                    <p>Logout</p>
                </a> </li>  
                
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Tenants</p>
                </a> </li> 
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Properties</p>
                </a> </li>
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Rent</p>
                </a> </li>
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Tasks</p>
                </a> </li> 
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Finance</p>
                </a> </li> 
                <li class="nav-item"> <a href="{% url 'orders:list' %}" class="nav-link"> <i class="nav-icon bi bi-people-fill"></i>
                    <p>Shopping list</p>
                </a> </li> 
                


            </ul> <!--end::Sidebar Menu-->
        </nav>
    </div> <!--end::Sidebar Wrapper-->
</aside> <!--end::Sidebar--> <!--begin::App Main-->

crm_main/core/templates/core/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Django CRM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'leads:list' %}">Leads</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'clients:list' %}">Clients</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'orders:list' %}">Orders</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'order_list' %}">OrdersNew</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:list' %}">Products</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout0</a>
        </li> -->
        <form action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="nav-link"
            style="border: none; background: none; cursor: pointer;">Logout</button>
        </form>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userprofile:signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>
{% if breadcrumbs %}
<div class="container">
  {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs%}
</div>
{% endif %}

crm_main/core/templates/core/partials/navigation.html
{% load static %}
   {% comment %} navigation {% endcomment %}
   <nav class="app-header navbar navbar-expand bg-body"> <!--begin::Container-->
    <div class="container-fluid"> <!--begin::Start Navbar Links-->
        <ul class="navbar-nav">
            <li class="nav-item"> <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button"> <i class="bi bi-list"></i> </a> </li>
            <li class="nav-item d-none d-md-block"> <a href="#" class="nav-link">Home</a> </li>
            <li class="nav-item d-none d-md-block"> <a href="#" class="nav-link">Contact</a> </li>
        </ul> <!--end::Start Navbar Links--> <!--begin::End Navbar Links-->
        <ul class="navbar-nav ms-auto"> <!--begin::Navbar Search-->
            <li class="nav-item"> <a class="nav-link" data-widget="navbar-search" href="#" role="button"> <i class="bi bi-search"></i> </a> </li> <!--end::Navbar Search--> <!--begin::Messages Dropdown Menu-->
            <li class="nav-item dropdown"> <a class="nav-link" data-bs-toggle="dropdown" href="#"> <i class="bi bi-chat-text"></i> <span class="navbar-badge badge text-bg-danger">3</span> </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end"> <a href="#" class="dropdown-item"> <!--begin::Message-->
                        <div class="d-flex">
                            <div class="flex-shrink-0"> <img src="{% static 'assets/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 rounded-circle me-3"> </div>
                            <div class="flex-grow-1">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-end fs-7 text-danger"><i class="bi bi-star-fill"></i></span>
                                </h3>
                                <p class="fs-7">Call me whenever you can...</p>
                                <p class="fs-7 text-secondary"> <i class="bi bi-clock-fill me-1"></i> 4 Hours Ago
                                </p>
                            </div>
                        </div> <!--end::Message-->
                    </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"> <!--begin::Message-->
                        <div class="d-flex">
                            <div class="flex-shrink-0"> <img src="{% static 'assets/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 rounded-circle me-3"> </div>
                            <div class="flex-grow-1">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-end fs-7 text-secondary"> <i class="bi bi-star-fill"></i> </span>
                                </h3>
                                <p class="fs-7">I got your message bro</p>
                                <p class="fs-7 text-secondary"> <i class="bi bi-clock-fill me-1"></i> 4 Hours Ago
                                </p>
                            </div>
                        </div> <!--end::Message-->
                    </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"> <!--begin::Message-->
                        <div class="d-flex">
                            <div class="flex-shrink-0"> <img src="{% static 'assets/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 rounded-circle me-3"> </div>
                            <div class="flex-grow-1">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-end fs-7 text-warning"> <i class="bi bi-star-fill"></i> </span>
                                </h3>
                                <p class="fs-7">The subject goes here</p>
                                <p class="fs-7 text-secondary"> <i class="bi bi-clock-fill me-1"></i> 4 Hours Ago
                                </p>
                            </div>
                        </div> <!--end::Message-->
                    </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li> <!--end::Messages Dropdown Menu--> <!--begin::Notifications Dropdown Menu-->
            <li class="nav-item dropdown"> <a class="nav-link" data-bs-toggle="dropdown" href="#"> <i class="bi bi-bell-fill"></i> <span class="navbar-badge badge text-bg-warning">15</span> </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end"> <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"> <i class="bi bi-envelope me-2"></i> 4 new messages
                        <span class="float-end text-secondary fs-7">3 mins</span> </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"> <i class="bi bi-people-fill me-2"></i> 8 friend requests
                        <span class="float-end text-secondary fs-7">12 hours</span> </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"> <i class="bi bi-file-earmark-fill me-2"></i> 3 new reports
                        <span class="float-end text-secondary fs-7">2 days</span> </a>
                    <div class="dropdown-divider"></div> <a href="#" class="dropdown-item dropdown-footer">
                        See All Notifications
                    </a>
                </div>
            </li> <!--end::Notifications Dropdown Menu--> <!--begin::Fullscreen Toggle-->
            <li class="nav-item"> <a class="nav-link" href="#" data-lte-toggle="fullscreen"> <i data-lte-icon="maximize" class="bi bi-arrows-fullscreen"></i> <i data-lte-icon="minimize" class="bi bi-fullscreen-exit" style="display: none;"></i> </a> </li> <!--end::Fullscreen Toggle--> <!--begin::User Menu Dropdown-->
            <li class="nav-item dropdown user-menu"> <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"> <img src="../../dist/assets/img/user2-160x160.jpg" class="user-image rounded-circle shadow" alt="User Image"> <span class="d-none d-md-inline">Alexander Pierce</span> </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end"> <!--begin::User Image-->
                    <li class="user-header text-bg-primary"> <img src="../../dist/assets/img/user2-160x160.jpg" class="rounded-circle shadow" alt="User Image">
                        <p>
                            Alexander Pierce - Web Developer
                            <small>Member since Nov. 2023</small>
                        </p>
                    </li> <!--end::User Image--> <!--begin::Menu Body-->
                    <li class="user-body"> <!--begin::Row-->
                        <div class="row">
                            <div class="col-4 text-center"> <a href="#">Followers</a> </div>
                            <div class="col-4 text-center"> <a href="#">Sales</a> </div>
                            <div class="col-4 text-center"> <a href="#">Friends</a> </div>
                        </div> <!--end::Row-->
                    </li> <!--end::Menu Body--> <!--begin::Menu Footer-->
                    <li class="user-footer"> <a href="#" class="btn btn-default btn-flat">Profile</a> <a href="#" class="btn btn-default btn-flat float-end">Sign out</a> </li> <!--end::Menu Footer-->
                </ul>
            </li> <!--end::User Menu Dropdown-->
        </ul> <!--end::End Navbar Links-->
    </div> <!--end::Container-->
</nav> <!--end::Header--> <!--begin::Sidebar-->