crm_main/client/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.client_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('add/', views.client_add, name='add'),
]

crm_main/crm_main/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from core.views import index
from userprofile.views import signup
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/products/', include('product.urls')),
    path('dashboard/orders/', include('order.urls')),
    path('dashboard/ordersnew/', include('ordernew.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/users/', include('userprofile.urls')),
    # path('sign-up/', signup, name='signup'),
    path('log-in/',views.LoginView.as_view(template_name='userprofile/login.html') ,name='login'),
    path('log-out/',views.LogoutView.as_view() ,name='logout'),
    # path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    # path('log-out/', views.LogoutView.as_view(), name='logout'),
    # path('tickets/', include('tickets.urls')),
    path('tickets/', include('ticket.urls')),
    path('properties/', include('property.urls')),
    path('tenants/', include('tenant.urls')),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
URL configuration for crm_main project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

crm_main/lead/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add_lead'),
]

crm_main/order/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='list'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'), #optimize the name here.
    path('add-order/', views.OrderCreateView.as_view(), name='add_order'), # changed orders_add to order_add
    path('<int:pk>/delete/', views.OrderDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.OrderUpdateView.as_view(), name='edit'),
    path('<int:pk>/add-product/', views.AddProductView.as_view(), name='add_product'),
]

crm_main/order/models.py
from django.db import models
from django.contrib.auth.models import User
from client.models import Client
from product.models import Product

# Create your models here.

class Order(models.Model):
    PENDING = 'pending'
    PROCESSING = 'processing'
    COMPLETED = 'completed'
    CANCELED = 'canceled'

    ORDER_STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (PROCESSING, 'Processing'),
        (COMPLETED, 'Completed'),
        (CANCELED, 'Canceled'),
    ]

    order_number = models.CharField(max_length=20, unique=True)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='orders', on_delete=models.CASCADE)  # Added field
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default=PENDING)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    shipment_company = models.CharField(max_length=100, blank=True, null=True)
    tracking_number = models.CharField(max_length=50, blank=True, null=True)
    shiping_fee = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    order_date = models.DateField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order {self.order_number}"
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, related_name='order_products', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_products', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.total_price = self.unit_price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

crm_main/order/forms.py
from django import forms
from .models import Order, OrderProduct

class AddOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = ('name', 'email', 'description', 'priority', 'status',)
        fields = ('order_number', 'client', 'status','total','status',) # should eidt order date here.

# ======================================================
        
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_number', 'created_by', 'client', 'status', 'total', 'shipment_company', 'tracking_number', 'shiping_fee']
        widgets = {
            'order_number': forms.TextInput(attrs={'class': 'form-control'}),
            'created_by': forms.Select(attrs={'class': 'form-control'}),
            'client': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'total': forms.NumberInput(attrs={'class': 'form-control'}),
            'shipment_company': forms.TextInput(attrs={'class': 'form-control'}),
            'tracking_number': forms.TextInput(attrs={'class': 'form-control'}),
            'shiping_fee': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class OrderProductForm(forms.ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['product', 'quantity', 'unit_price']
        widgets = {
            'product': forms.Select(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'unit_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'order_date': forms.NumberInput(attrs={'class': 'form-control'}),
        }
# this is used to create a formset for the OrderProduct model, it is used to create multiple OrderProduct objects at once.
# OrderProductFormSet = forms.inlineformset_factory(Order, OrderProduct, form=OrderProductForm, extra=1, can_delete=True) 

crm_main/order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Order, OrderProduct
from .forms import AddOrderForm, OrderForm, OrderProductForm
from django.contrib import messages
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views import View

class OrderListView(ListView):
    model = Order
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OrderListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Order List'
        return context

class OrderDetailView(DetailView):
    model = Order
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderProductForm()
        context['page_title'] = 'Order Detail'
        return context

    def get_queryset(self):
        queryset = super(OrderDetailView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))

class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super(OrderDeleteView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Delete Order'
        return context

class OrderCreateView(CreateView):
    model = Order
    fields = ('order_number', 'client', 'status', 'total', 'status',)
    success_url = reverse_lazy('orders:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add order'
        context['page_title'] = 'Create Order'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        messages.success(self.request, 'Order "{}" has been added successfully!'.format(self.object.order_number))
        return redirect(self.get_success_url())

class OrderUpdateView(UpdateView):
    model = Order
    fields = ('order_number', 'client', 'status', 'total', 'status',)
    success_url = reverse_lazy('orders:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit order'
        context['page_title'] = 'Update Order'
        return context

    def get_queryset(self):
        queryset = super(OrderUpdateView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        messages.success(self.request, 'Order "{}" has been updated successfully!'.format(self.object.order_number))
        return super().form_valid(form)

class AddProductView(CreateView):
    model = OrderProduct
    form_class = OrderProductForm
    template_name = 'order/add_product.html'
    success_url = reverse_lazy('orders:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.order = get_object_or_404(Order, pk=self.kwargs['pk'])
        messages.success(self.request, 'Product has been added to the order successfully!')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Add Product to Order'
        return context

crm_main/order/templates/order/order_detail copy.html
{% extends 'core/base.html' %} 

 {% block title %}orders details{% endblock %}

 {% block content %}
 <!-- ------------------------------------------------------- -->


 <div class="card">
	<div class="card-header"><strong>
		  {{ order.order_number }} 
		</strong>
	</div>
	<div class="card-body">
  
  
  
  <p class="card-text">
  <strong>Client: </strong>{{ order.client }}</p>
  
  <p class="card-text">
  <strong>Status: </strong>{{ order.status }}
  </p>
  
  <p class="card-text">
  <strong>Total: </strong>{{ order.total }}</p>
  
  <p class="card-text">
  <strong>Status: </strong>{{ order.status }}</p>
  
  <p class="card-text">
  <strong>Created_by: </strong>{{ order.created_by }}</p>
  
  <p class="card-text">
  <strong>Order_date: </strong>{{ order.order_date }}</p>
  
  <p class="card-text">
  <strong>Created_at: </strong>{{ order.created_at }}</p>
  
  <p class="card-text">
  <strong>Modified_at: </strong>{{ order.modified_at }}</p>
  
  <p class="card-text">
  <strong>ID: </strong>{{ order.id }}</p>
	  
	  
	</div>
  
</div>
<form id="order_delete_form" method="post" action="{% url 'orders:delete' order.id %}">
  {% csrf_token %}
</form>


  <br/><br/>
  <a href="{% url 'orders:list' %}" class="btn btn-primary">Back</a>
  <a href="{% url 'orders:edit' order.id %}" class="btn btn-info">Update Client</a>
  <!-- <a href="{% url 'orders:delete' order.id %}" class="btn btn-danger">Delete</a> -->
  <a href="#" onclick="document.getElementById('order_delete_form').submit();" class="btn btn-danger">Delete</a>
  

  <hr>
  <h2>Order Products new</h2>
    <ul>
        {% for order_product in object.order_products.all %}
            <li>
                <strong>{{ order_product.product }}</strong> - 
                Quantity: {{ order_product.quantity }} - 
                Price: {{ order_product.unit_price }}
                <!-- Add other fields as needed -->
            </li>
        {% empty %}
            <li>No products in this order.</li>
        {% endfor %}
    </ul>
  <hr>
  <hr>

  <!-- ------------------------------------------------------- display product below-->
  <!-- order below ------------------------------------------ -->
  <hr class="my-4">

  <h2 class="mb-6 text-xl">Order Details: Products</h2>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Order</th>
          <th>Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Total Price</th>
          <th>Order Date</th>
        </tr>
      </thead>
      <tbody>
        {% for product in order.order_products.all %}
        <tr>
          <td>{{ product.order }}</td>
          <td>{{ product.product }}</td>
          <td>{{ product.unit_price }}</td>
          <td>{{ product.quantity }}</td>
          <td>{{ product.total_price }}</td>
          <td>{{ product.order_date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- ------------------------------------------------------- form below -->
  <hr>



  <form method="post" action="{% url 'orders:add_product' order.id %}">
    {% csrf_token %}
  
    <div class="row">
      <div class="col-md-2"> <!-- Adjust the width here -->
        <div class="form-group">
          {{ form.as_p }}
        </div>
      </div>
    </div>
  
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

 {% endblock %}

crm_main/order/templates/order/order_detail.html
{% extends 'core/base.html' %} 

 {% block title %}orders details{% endblock %}

 {% block content %}
 <!-- ------------------------------------------------------- -->


 <div class="card">
	<div class="card-header"><strong>
		  {{ order.order_number }} 
		</strong>
	</div>
	<div class="card-body">
  
  
  
  <p class="card-text">
  <strong>Client: </strong>{{ order.client }}</p>
  
  <p class="card-text">
  <strong>Status: </strong>{{ order.status }}
  </p>
  
  <p class="card-text">
  <strong>Total: </strong>{{ order.total }}</p>
  
  <p class="card-text">
  <strong>Status: </strong>{{ order.status }}</p>
  
  <p class="card-text">
  <strong>Created_by: </strong>{{ order.created_by }}</p>
  
  <p class="card-text">
  <strong>Order_date: </strong>{{ order.order_date }}</p>
  
  <p class="card-text">
  <strong>Created_at: </strong>{{ order.created_at }}</p>
  
  <p class="card-text">
  <strong>Modified_at: </strong>{{ order.modified_at }}</p>
  
  <p class="card-text">
  <strong>ID: </strong>{{ order.id }}</p>
	  
	  
	</div>
  
</div>
<form id="order_delete_form" method="post" action="{% url 'orders:delete' order.id %}">
  {% csrf_token %}
</form>


  <br/><br/>
  <a href="{% url 'orders:list' %}" class="btn btn-primary">Back</a>
  <a href="{% url 'orders:edit' order.id %}" class="btn btn-info">Update Client</a>
  <!-- <a href="{% url 'orders:delete' order.id %}" class="btn btn-danger">Delete</a> -->
  <a href="#" onclick="document.getElementById('order_delete_form').submit();" class="btn btn-danger">Delete</a>
  

  <!-- <hr> -->

  <!-- ------------------------------------------------------- display product below-->
  <!-- order below ------------------------------------------ -->
  <hr class="my-4">

  <h2 class="mb-6 text-xl">Order Details: Products</h2>

  <div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Order</th>
                <th>Product</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Order Date</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            {% for product in object.order_products.all %}
            <tr>
                <td>{{ product.order }}</td>
                <td>{{ product.product }}</td>
                <td>{{ product.unit_price }}</td>
                <td>{{ product.quantity }}</td>
                <td>{{ product.total_price }}</td>
                <td>{{ product.order_date }}</td>
                <td>edit delete</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No products in this order.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


  <!-- ------------------------------------------------------- form below -->
  <hr>



  <form method="post" action="{% url 'orders:add_product' order.id %}">
    {% csrf_token %}
  
   
<!-- <hr> -->

<h2>Add products to order:</h2>
<div class="row">
  <div class="col-md-2">
    <div class="form-group d-flex align-items-center">
      <label for="id_product" class="form-label me-2">Product:</label>
      {{ form.product }}
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group d-flex align-items-center">
      <label for="id_unit_price" class="form-label me-2">Unit_Price:</label>
      {{ form.unit_price }}
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group d-flex align-items-center">
      <label for="id_quantity" class="form-label me-2">Quantity:</label>
      {{ form.quantity }}
    </div>
  </div>
</div>

  <br/>
    <div class="row">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
 {% endblock %}

crm_main/order/templates/order/order_form.html
{% extends 'core/base.html' %} 

 {% block title %}{{title}} {% endblock %}

 {% block content %}
 
 <h1>{{title}}</h1>
 <form method="POST" action=".">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
<a href="{% url 'orders:list' %}" class="btn btn-secondary">Back</a>
  <button type="submit" class="btn btn-secondary">Submit</button>

</form>

 {% endblock %}

crm_main/order/templates/order/order_list.html
{% extends 'core/base.html' %} 

 {% block title %} Orders List {% endblock %}

 {% block content %}
{% comment %}  
 <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">order_number</th>
        <th scope="col">Client</th>
        <th scope="col">status</th>
        <th scope="col">total</th>
        <!-- <th scope="col">shipment_company</th> -->
        <!-- <th scope="col">tracking_number</th> -->
        <!-- <th scope="col">shiping_fee</th> -->
        <th scope="col">Created_by</th>
        <th scope="col">order_date</th>
        <!-- <th scope="col">order_id 666</th> -->
        <!-- <th scope="col">created_by_id</th> -->
        <!-- <th scope="col">1</th> -->
        <th scope="col">Created_at</th>
        <th scope="col">Modified_at</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      
  {% if object_list %}
      {% for order in object_list %}
          <tr>
              <td>{{ order.order_number }}</td>
              <td>{{ order.client }}</td>
              <td>{{ order.status }}</td>
              <td>{{ order.total }}</td>
              <!-- <td>{{ order.shipment_company }}</td> -->
              <!-- <td>{{ order.tracking_number }}</td> -->
              <!-- <td>{{ order.shiping_fee }}</td> -->
              <td>{{ order.created_by }}</td>
              <td>{{ order.order_date }}</td>
              <!-- <td>{{ order.id }} 666</td> -->
              <!-- <td>{{ order.created_by_id }}</td> -->
              <td>{{ order.created_at }}</td>
              <td>{{ order.modified_at }}</td>
              <td><a href="{% url 'orders:detail' order.id %}">{{ order.id }}</a></td> 
        <!-- % url 'order' order.id %} -->
          </tr>
        

      {% endfor %}
  {% else %}
      <tr>
          <td colspan="9">No orders found</td>
      </tr>
  
  {% endif %}
  
      
        </tbody>
      
      </table>
      <a href="{% url 'orders:add_order' %}" class="btn btn-danger">Add order</a>
 {% endcomment %}




      <div class="card mb-4">
        <div class="card-header">
            <h3 class="card-title">Tenants Information</h3>
        </div> <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>Country</th>
                        <th>Occupation</th>
                        {% comment %} <th>Occupation</th> {% endcomment %}
                        <th>Phone Number</th>
                        <th>Email Address</th>
                        <th>Property ID</th>
                        <th>Unit Number</th>
                        {% comment %} <th>Lease Start Date</th> {% endcomment %}
                        {% comment %} <th>Lease End Date</th> {% endcomment %}
                        <th>Rent Amount</th>
                        {% comment %} <th>Deposit Amount</th> {% endcomment %}
                        <th>Payment Method</th>
                        <th>Agent</th>
                        {% comment %} <th>Progress</th>
                        <th style="width: 40px">Label</th> {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                    <tr class="align-middle">
                        <td>1.</td>
                        
                        <td>Update software</td>
                        <td>1</td>
                        <td>1</td>
                        <td>1</td>
                        <td>1</td>
                        <td>1</td>
                        <tr>
                          <td>1</td>
                          <td>Alice Johnson</td>
                          <td>Female</td>
                          <td>Ireland</td>
                          <td>Software Engineer</td>
                          <td>0831234567</td>
                          <td>alice.johnson@email.ie</td>
                          <td>P001</td>
                          <td>A101</td>
                          <td>1200</td>
                          <td>Credit Card</td>
                          <td>John O'Connor</td>
                      </tr>
                      <tr>
                          <td>2</td>
                          <td>Michael Smith</td>
                          <td>Male</td>
                          <td>UK</td>
                          <td>Data Analyst</td>
                          <td>0857654321</td>
                          <td>michael.smith@email.uk</td>
                          <td>P002</td>
                          <td>B201</td>
                          <td>950</td>
                          <td>Direct Debit</td>
                          <td>Sarah Kelly</td>
                      </tr>
                      <tr>
                          <td>3</td>
                          <td>Chen Wei</td>
                          <td>Male</td>
                          <td>China</td>
                          <td>Business Manager</td>
                          <td>0862345678</td>
                          <td>chen.wei@email.cn</td>
                          <td>P003</td>
                          <td>C301</td>
                          <td>1050</td>
                          <td>Bank Transfer</td>
                          <td>Laura Byrne</td>
                      </tr>
                      <tr>
                          <td>4</td>
                          <td>Priya Gupta</td>
                          <td>Female</td>
                          <td>India</td>
                          <td>Accountant</td>
                          <td>0879876543</td>
                          <td>priya.gupta@email.in</td>
                          <td>P004</td>
                          <td>D401</td>
                          <td>1100</td>
                          <td>Cash</td>
                          <td>David Walsh</td>
                      </tr>
                      <tr>
                          <td>5</td>
                          <td>James O'Leary</td>
                          <td>Male</td>
                          <td>Ireland</td>
                          <td>Graphic Designer</td>
                          <td>0894561234</td>
                          <td>james.oleary@email.ie</td>
                          <td>P005</td>
                          <td>E501</td>
                          <td>1300</td>
                          <td>Standing Order</td>
                          <td>Anna Murphy</td>
                      </tr>
                        {% comment %} <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                            </div>
                        </td>
                        <td><span class="badge text-bg-danger">55%</span></td> {% endcomment %}
                    </tr>

                    
                </tbody>
            </table>
        </div> <!-- /.card-body -->


        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-end">
                <li class="page-item"> <a class="page-link" href="#">&laquo;</a> </li>
                <li class="page-item"> <a class="page-link" href="#">1</a> </li>
                <li class="page-item"> <a class="page-link" href="#">2</a> </li>
                <li class="page-item"> <a class="page-link" href="#">3</a> </li>
                <li class="page-item"> <a class="page-link" href="#">&raquo;</a> </li>
            </ul>
        </div>
    </div> <!-- /.card -->
 {% endblock %}


 

crm_main/order/templates/order/orders_add.html
{% extends 'core/base.html' %} 

 {% block title %}Add order {% endblock %}

 {% block content %}
 
 <form method="POST" action=".">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
<a href="{% url 'orders:list' %}" class="btn btn-secondary">Back</a>
  <button type="submit" class="btn btn-secondary">Add order</button>

</form>

 {% endblock %}

crm_main/order/templates/order/orders_edit.html
{% extends 'core/base.html' %} 

 {% block title %}Edit Orders{% endblock %}

 {% block content %}
 
 <form method="POST" action=".">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
<a href="{% url 'orders:list' %}" class="btn btn-secondary">Back</a>
  <button type="submit" class="btn btn-secondary">Submit</button>

</form>

 {% endblock %}

crm_main/order/templates/order/orders_list.html
{% extends 'core/base.html' %} 

 {% block title %} Orders List {% endblock %}

 {% block content %}
 
 <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">order_number</th>
        <th scope="col">Client</th>
        <th scope="col">status</th>
        <th scope="col">total</th>
        <!-- <th scope="col">shipment_company</th> -->
        <!-- <th scope="col">tracking_number</th> -->
        <!-- <th scope="col">shiping_fee</th> -->
        <th scope="col">Created_by</th>
        <th scope="col">order_date</th>
        <!-- <th scope="col">order_id 666</th> -->
        <!-- <th scope="col">created_by_id</th> -->
        <!-- <th scope="col">1</th> -->
        <th scope="col">Created_at</th>
        <th scope="col">Modified_at</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      
  {% if orders %}
      {% for order in orders %}
          <tr>
              <td>{{ order.order_number }}</td>
              <td>{{ order.client }}</td>
              <td>{{ order.status }}</td>
              <td>{{ order.total }}</td>
              <!-- <td>{{ order.shipment_company }}</td> -->
              <!-- <td>{{ order.tracking_number }}</td> -->
              <!-- <td>{{ order.shiping_fee }}</td> -->
              <td>{{ order.created_by }}</td>
              <td>{{ order.order_date }}</td>
              <!-- <td>{{ order.id }} 666</td> -->
              <!-- <td>{{ order.created_by_id }}</td> -->
              <td>{{ order.created_at }}</td>
              <td>{{ order.modified_at }}</td>
              <td><a href="{% url 'orders:detail' order.id %}">{{ order.id }}</a></td> 
        <!-- % url 'order' order.id %} -->
          </tr>
        

      {% endfor %}
  {% else %}
      <tr>
          <td colspan="9">No orders found</td>
      </tr>
  
  {% endif %}
  
      
        </tbody>
      
      </table>
      <a href="{% url 'orders:add' %}" class="btn btn-danger">Add order</a>
 {% endblock %}


 