crm_main/crm_main/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from core.views import index
from userprofile.views import signup
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/products/', include('product.urls')),
    path('dashboard/orders/', include('order.urls')),
    path('dashboard/ordersnew/', include('ordernew.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/users/', include('userprofile.urls')),
    # path('sign-up/', signup, name='signup'),
    path('log-in/',views.LoginView.as_view(template_name='userprofile/login.html') ,name='login'),
    path('log-out/',views.LogoutView.as_view() ,name='logout'),
    # path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    # path('log-out/', views.LogoutView.as_view(), name='logout'),
    # path('tickets/', include('tickets.urls')),
    path('tickets/', include('ticket.urls')),
    path('properties/', include('property.urls')),
    path('tenants/', include('tenant.urls')),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
URL configuration for crm_main project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

crm_main/lead/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add_lead'),
]

crm_main/lead/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    # team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
            return self.name
    

class Comment(models.Model):
    # team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

crm_main/lead/forms.py
from django import forms
from .models import Lead, Comment

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

crm_main/lead/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.contrib.auth.decorators import login_required
# from .forms import AddLeadForm, AddCommentForm
from .forms import AddCommentForm
from .models import Lead
from django.contrib import messages
from client.models import Client
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views import View

class LeadListView(ListView):
    model = Lead
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LeadListView, self).dispatch(*args, **kwargs)


    def get_queryset(self): # this is the method that is called when the view is loaded, it returns the queryset that is used to populate the list of leads.
        queryset = super(LeadListView,self).get_queryset()
        return queryset.filter(created_by=self.request.user, converted_to_client=False)


class LeadDetailView(DetailView):
    model = Lead
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):#*args is used to pass any number of arguments to the method, **kwargs is used to pass any additional arguments to the method.
        return super().dispatch(*args, **kwargs) # this method is used to check if the user is logged in before they can access the view. **kwargs is used to pass any additional arguments to the method.
    
    def get_context_data(self, **kwargs): # this method is used to pass additional context to the template, in this case, the AddCommentForm form.
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        # context['fileform'] = AddFileForm()

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        # team = self.request.user.userprofile.active_team

        # return queryset.filter(team=team, pk=self.kwargs.get('pk'))
        return queryset.filter(pk=self.kwargs.get('pk'))

class LeadDeleteView(DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
        
    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        # team = self.request.user.userprofile.active_team
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))
    
    # skip the get_queryset method and use the get method instead.
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    


    
class LeadUpdateView(UpdateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit lead'

        return context

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        # team = self.request.user.userprofile.active_team
        return queryset.filter(pk=self.kwargs.get('pk'))
    
    # add the form_valid method to add a success message
    def form_valid(self, form):
        # messages.success(self.request, "Lead updated successfully.")  # Add success message here
        messages.success(self.request, 'Lead "{}" has been updated successfully!'.format(self.object.name))
        return super().form_valid(form)

class LeadCreateView(CreateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs): # this method is used to pass additional context to the template
        context = super().get_context_data(**kwargs)
        # team = self.request.user.userprofile.get_active_team()
        # context['team'] = team
        context['title'] = 'Add lead'

        return context

    def form_valid(self, form): # this method is called when the form is valid, it saves the form and adds the created_by field
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        # self.object.team = self.request.user.userprofile.get_active_team()
        self.object.save()
        messages.success(self.request, 'Lead "{}" has been added successfully!'.format(self.object.name))
        return redirect(self.get_success_url())
    
# class AddCommentView(LoginRequiredMixin, View):
class AddCommentView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            # comment.team = self.request.user.userprofile.get_active_team()
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)

class ConvertToClientView(View):
    def get(self,request,*args,**kwargs):
        pk = self.kwargs.get('pk')
        lead = get_object_or_404(Lead, created_by=request.user,pk=pk)
        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            # team=team,
        )

        lead.converted_to_client = True
        lead.save()

        # Convert lead comments to client comments

        # comments = lead.comments.all()

        # for comment in comments:
        #     ClientComment.objects.create(
        #         client = client,
        #         content = comment.content,
        #         created_by = comment.created_by,
        #         team = team
        #     )
        
        # Show message and redirect

        messages.success(request, 'The lead was converted to a client.')

        return redirect('leads:list')

crm_main/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %} 

 {% block title %}Leads details{% endblock %}

 {% block content %}
 <!-- ------------------------------------------------------- -->



 <div class="card">
	<div class="card-header"><strong>
		  {{ lead.name }} 
		</strong>
	</div>
	<div class="card-body">
  
  
  
  <p class="card-text">
  <strong>Email: </strong>{{ lead.email }}</p>
  
  <p class="card-text">
  <strong>description: </strong>{{ lead.description }}
  </p>
  
  <p class="card-text">
  <strong>priority: </strong>{{ lead.priority }}</p>
  
  <p class="card-text">
  <strong>status: </strong>{{ lead.status }}</p>
  
  <p class="card-text">
  <strong>created_by: </strong>{{ lead.created_by }}</p>
  
  <p class="card-text">
  <strong>created_at: </strong>{{ lead.created_at }}</p>
  
  <p class="card-text">
  <strong>modified_at: </strong>{{ lead.modified_at }}</p>
  
  <p class="card-text">
  <strong>ID: </strong>{{ lead.id }}</p>
	  
	  
	</div>
  
</div>

<form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
  {% csrf_token %}
</form>

  <br/><br/>
  <a href="{% url 'leads:list' %}" class="btn btn-primary">Back</a>
  <a href="{% url 'leads:edit' lead.id %}" class="btn btn-info">Update Record</a>
  <a href="{% url 'leads:convert' lead.id %}" class="btn btn-success">Convert to Client</a>
  <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="btn btn-danger">Delete</a>
  
  <!-- comment below ------------------------------------------ -->
  <hr class="my-4">

        <h2 class="mb-6 text-xl">Comments</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %} <!-- lead.comments.all is the related name in the model -->
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_comment' lead.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-red">Submit</button>
        </form>
 <!-- ------------------------------------------------------- -->

 {% endblock %}

crm_main/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %} 

 {% block title %}{{title}}{% endblock %}

 {% block content %}
 
 <form method="POST" action=".">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
<a href="{% url 'leads:list' %}" class="btn btn-secondary">Back</a>
  <button type="submit" class="btn btn-secondary">Submit</button>

</form>

 {% endblock %}

crm_main/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %} 

 {% block title %} Leads List {% endblock %}

 {% block content %}

 
 <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Description</th>
        <th scope="col">Priority</th>
        <th scope="col">Status</th>
        <th scope="col">Created_by</th>
        <th scope="col">Created_at</th>
        <th scope="col">Modified_at</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      
  {% if object_list %}
      {% for lead in object_list %}
          <tr>
              <td>{{ lead.name }}</td>
              <td>{{ lead.email }}</td>
              <td>{{ lead.description }}</td>
              <td>{{ lead.priority }}</td>
              <td>{{ lead.status }}</td>
              <td>{{ lead.created_by }}</td>
              <td>{{ lead.created_at }}</td>
              <td>{{ lead.modified_at }}</td>
              <td><a href="{% url 'leads:detail' lead.id %}">{{ lead.id }}</a></td> 
        <!-- % url 'lead' lead.id %} -->
          </tr>
        

      {% endfor %}
  {% else %}
      <tr>
          <td colspan="9">No leads found</td>
      </tr>
  
  {% endif %}
  
      
        </tbody>
      
      </table>

      <a href="{% url 'leads:add_lead' %}" class="btn btn-danger">Add lead</a>
 {% endblock %}

 

crm_main/lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %} 

 {% block title %}Leads details{% endblock %}

 {% block content %}
 <!-- ------------------------------------------------------- -->



 <div class="card">
	<div class="card-header"><strong>
		  {{ lead.name }} 
		</strong>
	</div>
	<div class="card-body">
  
  
  
  <p class="card-text">
  <strong>Email: </strong>{{ lead.email }}</p>
  
  <p class="card-text">
  <strong>description: </strong>{{ lead.description }}
  </p>
  
  <p class="card-text">
  <strong>priority: </strong>{{ lead.priority }}</p>
  
  <p class="card-text">
  <strong>status: </strong>{{ lead.status }}</p>
  
  <p class="card-text">
  <strong>created_by: </strong>{{ lead.created_by }}</p>
  
  <p class="card-text">
  <strong>created_at: </strong>{{ lead.created_at }}</p>
  
  <p class="card-text">
  <strong>modified_at: </strong>{{ lead.modified_at }}</p>
  
  <p class="card-text">
  <strong>ID: </strong>{{ lead.id }}</p>
	  
	  
	</div>
  
</div>

  <br/><br/>
  <a href="{% url 'leads_list' %}" class="btn btn-primary">Back</a>
  <a href="{% url 'leads_edit' lead.id %}" class="btn btn-info">Update Record</a>
  <a href="{% url 'leads_convert' lead.id %}" class="btn btn-success">Convert to Client</a>
  <a href="{% url 'leads_delete' lead.id %}" class="btn btn-danger">Delete</a>
  

 <!-- ------------------------------------------------------- -->

 {% endblock %}

crm_main/lead/templates/lead/leads_edit.html
{% extends 'core/base.html' %} 

 {% block title %}Edit leads{% endblock %}

 {% block content %}
 
 <form method="POST" action=".">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
<a href="{% url 'leads_list' %}" class="btn btn-secondary">Back</a>
  <button type="submit" class="btn btn-secondary">Submit</button>

</form>

 {% endblock %}

crm_main/lead/templates/lead/leads_list.html
{% extends 'core/base.html' %} 

 {% block title %} Leads List {% endblock %}

 {% block content %}
 
 <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Description</th>
        <th scope="col">Priority</th>
        <th scope="col">Status</th>
        <th scope="col">Created_by</th>
        <th scope="col">Created_at</th>
        <th scope="col">Modified_at</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      
  {% if leads %}
      {% for lead in leads %}
          <tr>
              <td>{{ lead.name }}</td>
              <td>{{ lead.email }}</td>
              <td>{{ lead.description }}</td>
              <td>{{ lead.priority }}</td>
              <td>{{ lead.status }}</td>
              <td>{{ lead.created_by }}</td>
              <td>{{ lead.created_at }}</td>
              <td>{{ lead.modified_at }}</td>
              <td><a href="{% url 'leads_detail' lead.id %}">{{ lead.id }}</a></td> 
        <!-- % url 'lead' lead.id %} -->
          </tr>
        

      {% endfor %}
  {% else %}
      <tr>
          <td colspan="9">No leads found</td>
      </tr>
  
  {% endif %}
  
      
        </tbody>
      
      </table>

 {% endblock %}


 